name: Run MongoDB tests

on: 
  push:
  pull_request:
  workflow_dispatch:

env:
  RUN_MONGODB_TEST: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Build talosplus
        run: go build .
        working-directory: cmd/talosplus/

      - name: Unit Tests
        run: go test ./test/...